<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IniciarSesion</name>
   <tag></tag>
   <elementGuidId>8e9e4bfc-2a4a-4b70-a592-401dbbaae70b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div/div/div/div[2]/form/fieldset/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-wrapper&quot;]/div/div/div/div[2]/form/fieldset/input</value>
   </webElementProperties>
</WebElementEntity>
